# Generated by Django 6.0.5 on 2026-05-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuicao',
            name='pagamento_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
    ]
