# Generated by Django 6.0.5 on 2026-05-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentes', '0002_contribuicao_pagamento_id_contribuicao_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribuicao',
            old_name='data',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='pix_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contribuicao',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='pagamento_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contribuicao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
    ]
